#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-tdiff
Version  : 0.3.3
Release  : 5
URL      : https://rubygems.org/downloads/tdiff-0.3.3.gem
Source0  : https://rubygems.org/downloads/tdiff-0.3.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
Patch1: 0001-Fix-rspec-version.patch

%description
# TDiff
* [Source](https://github.com/postmodern/tdiff)
* [Issues](https://github.com/postmodern/tdiff/issues)
* Postmodern (postmodern.mod3 at gmail.com)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n tdiff-0.3.3
gem spec %{SOURCE0} -l --ruby > rubygem-tdiff.gemspec
%patch1 -p1

%build
gem build rubygem-tdiff.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
tdiff-0.3.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/tdiff-0.3.3
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/tdiff-0.3.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/tdiff-0.3.3/ri/TDiff/Unordered/cdesc-Unordered.ri
/usr/lib64/ruby/gems/2.2.0/doc/tdiff-0.3.3/ri/TDiff/Unordered/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tdiff-0.3.3/ri/TDiff/Unordered/tdiff_recursive_unordered-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tdiff-0.3.3/ri/TDiff/Unordered/tdiff_unordered-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tdiff-0.3.3/ri/TDiff/cdesc-TDiff.ri
/usr/lib64/ruby/gems/2.2.0/doc/tdiff-0.3.3/ri/TDiff/tdiff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tdiff-0.3.3/ri/TDiff/tdiff_each_child-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tdiff-0.3.3/ri/TDiff/tdiff_equal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tdiff-0.3.3/ri/TDiff/tdiff_recursive-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tdiff-0.3.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/tdiff-0.3.3/ri/page-ChangeLog_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/tdiff-0.3.3/ri/page-LICENSE_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/tdiff-0.3.3/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/.document
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/.gemtest
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/.rspec
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/.yardopts
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/ChangeLog.md
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/README.md
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/gemspec.yml
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/lib/tdiff.rb
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/lib/tdiff/tdiff.rb
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/lib/tdiff/unordered.rb
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/lib/tdiff/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/spec/classes/node.rb
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/spec/helpers/trees.rb
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/spec/tdiff_examples.rb
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/spec/tdiff_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/spec/unordered_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/tdiff-0.3.3/tdiff.gemspec
/usr/lib64/ruby/gems/2.2.0/specifications/tdiff-0.3.3.gemspec
